services:
  app:
    image: partsbin
    ports: 
      - 8080:80
    volumes:
      # Update the first part of this (before the ':') to somewhere safe
      - ~/Dropbox/appdata/partsbin/data:/data
volumes:
  data:


